package com.example.eventbus.demo.dao.entity;

import java.util.Date;

public class EventLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.gmt_create
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.gmt_modified
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.rf_no
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String rfNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.trace_id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String traceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.event
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String eventLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.op_user
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String opUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.id
     *
     * @return the value of event_log.id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.id
     *
     * @param id the value for event_log.id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.gmt_create
     *
     * @return the value of event_log.gmt_create
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.gmt_create
     *
     * @param gmtCreate the value for event_log.gmt_create
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.gmt_modified
     *
     * @return the value of event_log.gmt_modified
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.gmt_modified
     *
     * @param gmtModified the value for event_log.gmt_modified
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.rf_no
     *
     * @return the value of event_log.rf_no
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public String getRfNo() {
        return rfNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.rf_no
     *
     * @param rfNo the value for event_log.rf_no
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setRfNo(String rfNo) {
        this.rfNo = rfNo == null ? null : rfNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.trace_id
     *
     * @return the value of event_log.trace_id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.trace_id
     *
     * @param traceId the value for event_log.trace_id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId == null ? null : traceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.event
     *
     * @return the value of event_log.event
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.event
     *
     * @param event the value for event_log.event
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.event_log
     *
     * @return the value of event_log.event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public String getEventLog() {
        return eventLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.event_log
     *
     * @param eventLog the value for event_log.event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setEventLog(String eventLog) {
        this.eventLog = eventLog == null ? null : eventLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log.op_user
     *
     * @return the value of event_log.op_user
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public String getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log.op_user
     *
     * @param opUser the value for event_log.op_user
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    public void setOpUser(String opUser) {
        this.opUser = opUser == null ? null : opUser.trim();
    }
}