package com.example.eventbus.demo.dao.entity;

import java.util.Date;

public class IpConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.id
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.gmt_create
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.gmt_modified
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.ip
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.last_scan_time
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Date lastScanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.scan_times
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Long scanTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.source
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.remarks
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.is_del
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.id
     *
     * @return the value of ip_config.id
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.id
     *
     * @param id the value for ip_config.id
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.gmt_create
     *
     * @return the value of ip_config.gmt_create
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.gmt_create
     *
     * @param gmtCreate the value for ip_config.gmt_create
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.gmt_modified
     *
     * @return the value of ip_config.gmt_modified
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.gmt_modified
     *
     * @param gmtModified the value for ip_config.gmt_modified
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.ip
     *
     * @return the value of ip_config.ip
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.ip
     *
     * @param ip the value for ip_config.ip
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.last_scan_time
     *
     * @return the value of ip_config.last_scan_time
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public Date getLastScanTime() {
        return lastScanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.last_scan_time
     *
     * @param lastScanTime the value for ip_config.last_scan_time
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setLastScanTime(Date lastScanTime) {
        this.lastScanTime = lastScanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.scan_times
     *
     * @return the value of ip_config.scan_times
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public Long getScanTimes() {
        return scanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.scan_times
     *
     * @param scanTimes the value for ip_config.scan_times
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setScanTimes(Long scanTimes) {
        this.scanTimes = scanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.source
     *
     * @return the value of ip_config.source
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.source
     *
     * @param source the value for ip_config.source
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.remarks
     *
     * @return the value of ip_config.remarks
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.remarks
     *
     * @param remarks the value for ip_config.remarks
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_config.is_del
     *
     * @return the value of ip_config.is_del
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_config.is_del
     *
     * @param isDel the value for ip_config.is_del
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}