package com.example.eventbus.demo.service.model;

/**
 * @name: task_event
 * @description:
 * @author: zhxy
 * @create: 2022/8/14 9:18
 **/
public class EventLogDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.rf_no
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String rfNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.trace_id
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String traceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.event
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String eventLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log.op_user
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    private String opUser;
}
