package com.example.eventbus.demo.service.model;

import java.util.Date;

/**
 * @name: task_event
 * @description:
 * @author: zhxy
 * @create: 2022/8/14 9:07
 **/
public class IpConfigDto {


    /**
     * ip地址
     */
    private String ip;

    /**
     *来源
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private String source;

    /**
     * 备注
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_config.is_del
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    private Integer isDel;
}
