package com.example.eventbus.demo.dao.mapper;

import com.example.eventbus.demo.dao.entity.EventLog;
import com.example.eventbus.demo.dao.entity.EventLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int insert(EventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int insertSelective(EventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    List<EventLog> selectByExample(EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    EventLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int updateByExampleSelective(@Param("record") EventLog record, @Param("example") EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int updateByExample(@Param("record") EventLog record, @Param("example") EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int updateByPrimaryKeySelective(EventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbg.generated Sun Aug 14 09:34:25 SGT 2022
     */
    int updateByPrimaryKey(EventLog record);
}