package com.example.eventbus.demo.dao.mapper;

import com.example.eventbus.demo.dao.entity.IpConfig;
import com.example.eventbus.demo.dao.entity.IpConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IpConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int insert(IpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int insertSelective(IpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    List<IpConfig> selectByExample(IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    IpConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int updateByExampleSelective(@Param("record") IpConfig record, @Param("example") IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int updateByExample(@Param("record") IpConfig record, @Param("example") IpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int updateByPrimaryKeySelective(IpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_config
     *
     * @mbg.generated Sun Aug 14 01:06:21 SGT 2022
     */
    int updateByPrimaryKey(IpConfig record);
}